# global settings for Solaris 11 with ISC DHCP ...
$omshell=		"/sbin/omshell";			# full path to omshell
$dhcpd4_leases_file=	"/var/db/isc-dhcp/dhcpd4.leases";	# full path to the dhcp4d.leases file (generated by ISC DHCP)
$dhcpd4_conf_file=	"/etc/inet/dhcpd4.conf";		# full path to the dhcpd4.conf file

$thisOS=`/bin/uname -s`;chomp $thisOS;
if ($thisOS eq 'SunOS') {
	# global settings for Solaris 11 with ISC DHCP ...
	$omshell=		"/sbin/omshell";			# full path to omshell
	$dhcpd4_leases_file=	"/var/db/isc-dhcp/dhcpd4.leases";	# full path to the dhcp4d.leases file (generated by ISC DHCP)
	$dhcpd4_conf_file=	"/etc/inet/dhcpd4.conf";		# full path to the dhcpd4.conf file
}
if ( $thisOS eq 'Linux') {
	# global settings for Linux with ISC DHCP ...
	$omshell=		"/usr/bin/omshell";			# full path to omshell
	$dhcpd4_leases_file=	"/var/lib/dhcpd/dhcpd.leases";		# full path to the dhcp4d.leases file (generated by ISC DHCP)
	$dhcpd4_conf_file=	"/etc/dhcp/dhcpd.conf";			# full path to the dhcpd4.conf file
}

$nr_of_backups=		50;						# number of backups to keep in /tmp
# END OF global settings

